name: books_app_client
description: Books app built with Flutter.

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_animate: ^4.3.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9
  mocktail: ^1.0.2
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.9
  wakelock_plus: ^1.1.4
  lottie: ^2.7.0
  flutter_cached_pdfview: ^0.4.2
  envied: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  envied_generator: ^0.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie_animations/
